export const dataAfiliasi = [
  {
    logo : "/logo/logo_phi.png",
    url : "/afiliasi/phi",
    title: "Public Health Innovators (PHI)",
    short : "PHI",
    color: "blue",
    desc: "Subunit yang bergerak pada bidang kesehatan masyakarat melalui riset, inovasi dan pengabdian. Tujuan dari subunit ini adalah menginisiasi terbentuknya generasi Aceh yang sehat dan makmur dengan mengembangkan strategi penyelesaian terhadap permasalahan kesehatan, serta menjadi role model untuk Indonesia dan dunia",
  },
  {
    logo : "/logo/logo_respace.png",
    url : "/afiliasi/respace",
    color: "yellow",
    title: "Creativemakerspace (RESPACE)",
    short : "RESPACE",
    desc: "subunit yang bergerak pada bidang kesenian, kreatifitas, dan bisnis. Tujuan subunit ini adalah menciptakan generasi yang kreatif & inovatif melalui pendekatan kesenian serta menumbuh dan mengembangkan potensi entrepreneurship pemuda",
  },
  {
    logo : "/logo/logo_gforce.png",
    url : "/afiliasi/gforce",
    title: "Generation of Fundamental Capacity Educator (G-FORCE)",
    short : "G-FORCE",
    color: "red",
    desc: "sub-unit yang bergerak dibidang pelatihan softskills terpadu dengan menerapkan kurikulum dan trainer berstandar nasional dan internasional. Tujuan dari subunit ini adalah meningkatkan kualitas softskills dan membentuk kader SDM yang unggul",
  },
  {
    logo : "/logo/logo_thelper.png",
    url : "/afiliasi/thelper",
    title: "Team Health Professional Educator and Researcher",
    short : "THELPER",
    color: "cyan",
    desc: "subunit yang bergerak dibidang  Interprofessional Education (IPE) dan Interprofessional Collaboration (IPC) dalam bentuk riset dan pendidikan kesehatan . Tujuan dari sub-unit ini adalah untuk meningkatkan kualitas dan mengembangkan kemampuan riset dan kolaborasi calon tenaga kesehatan",
  },
  {
    logo : "/logo/logo_pintoid.png",
    url : "/afiliasi/pintoid",
    title: "PINTO.ID",
    short : "PINTO.ID",
    color: "red",
    desc: "subunit yang bergerak pada promosi dan edukasi sejarah, budaya, dan pariwisata Aceh. Tujuan subunit ini adalah melestarikan dan memprosikan sejarah, budaya, dan pariwisata Aceh agar generasi tetap terjaga dan dikenal oleh Indonesia dan dunia",
  },
  {
    logo : "/logo/logo_rakansmong.png",
    url : "/afiliasi/rakansmong",
    title: "Relawan Kebencanaan Aneuk Nanggre SMONG (RAKAN-SMONG)",
    short : "RAKAN-SMONG",
    color: "amber",
    desc: "subunit yang bergerak pada bidang Pengurangan Resiko Bencana (PRB) berbasis spiritual, kearifan lokal, dan kesenian. Tujuan subunit ini adalah menciptakan",
  },
  {
    logo : "/logo/logo_safe.png",
    url : "/afiliasi/safe",
    title: "Supportive Aid Facilitator for Emergency (SAFE)",
    short : "SAFE",
    color: "green",
    desc: "subunit yang bergerak pada bidang Pertolongan Pertama pada Kecelakaan (P3K) melalui pelatihan dan kaderisasi. Tujuan subunit ini adalah menciptakan generasi dengan kemampuan pertolongan pertama yang benar dan mampu mengajarkannya kepada orang lain",
  },
];
